name: Build and Push Docker Image

on:
  # release:
  #   types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        default: 'latest'
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags:
                  ${{ secrets.DOCKERHUB_USERNAME }}/deepseek-free-api:${{ github.event.inputs.tag }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                platforms: linux/amd64,linux/arm64
